const versionLog = {
  'v.1.2.19': [
    'Åpne lenker til NVDB og Geonorge i ny fane',
    'Fikse bug som oppstår når brukeren zoomer inn, går frem og zoomer ut',
    'Søkefelt like stort som forslag under',
    'Tynn ramme på søkemeny og sideinformasjon',
  ],
  'v1.2.18': [
    'Sentrere tilbakemelding og feilmeldingsskjema',
    'Disable knapp for tilbake til hovedkart når brukeren er i zoom-modus',
    'Legge lukkeknappen på linje med knappene på venstre side',
    'Større skriftstørrelse på overskifter i bildeinfo',
    'Lik padding på alle tabs',
    'Aktiv tab "Om" fra start',
  ],
  'v1.2.17': [
    'Max bredde på sideinformasjonen',
    'Klikke på skjul/vis minikart',
    'Ta vekk innstillingsknappen',
    'Fikse buggy vis/skjul oppstartsmelding',
    'Lenker til Geonorge og NVDB',
  ],
  'v1.2.16': [
    'Velkomstmelding og sideinformasjon er nå samme komponent',
    'Teksten og tabs er oppdatert',
    'Zoom inn brukeren noen hakk dersom appen ikke finner bilder der den klikker (gjelder kun zoom-nivåer mindre enn 8)',
    'Rundede kanter på scrollbar i bildeinfo',
    'Fikse hoppende knapper i Chrome/Edge',
    'Link til vegkart oransje med ikonet når du hovrer',
    'Zoom nivå til vegkart 14',
    'Brukeren kan klikke på "skjema" for å åpne feilmeldingsskjema/tilbakemeldingsskjema. Den har også blitt stylet',
    'Tilbake til stort kart ved å klikke på minikartet',
    'Gjør oppslag på vegsystemreferanse til NVDB uansett år',
  ],
  'v1.2.15': [
    'Flyttet minibildet til øvre venstre hjørnet, endret styling og la til informasjonsknapp',
    'Tok tilbake knapp/ikon for bildemodus fra hovedkartet',
    'Endret zoom-nivå på lenke til vegkart til 13 ',
    'Fylke under kommune og ny header i informasjonsboksen',
    'Stylet alle scrollbarer',
    'Bedre skalering av informasjonsboks og minikart',
    'Lik border radius og skygge på lignende elementer',
    'Nytt instillingsikon',
    'Gjenommsiktighet på bakgrunner og ikke tekst/andre ting',
    'Ikoner i fargeforklareren og ikke sirkler',
    'Versjonslogg (redesign av velkomstvindu/info)',
    'Filtrere på vegkategori ved spørring om vegsystemreferanse fra NVDB (2019 og eldre)',
  ],
};

export { versionLog };
